### ISSUE TITLE
Arduino_UNO_R3 footprint is flipped

### ISSUE THREAD

**Issue by gwideman** [g200kg/kicad-lib-arduino#3]
I'm not sure if it's intentional, but the geometry for the footprint for the Arduino_UNO_R3 is as seen from the back side, not from the component side, as I would have expected.  Is there a rationale for this?  I don't see how this would help either placing an UNO in a project, or creating a clone UNO, or creating a shield.
It's not fatal, of course, because you can just place the footprint flipped... so long as you notice!

**Comment by CommanderGL** [comment]
This library doesn't contain the uno.

**Comment by gwideman** [comment]
Huh! Apparently I posted this issue on the wrong project! What was I thinking?

FWIW, the issue is valid, but it's for the Kicad supplied "module" library.

**Comment by CommanderGL** [comment]
wow didn't expect you to respond as it's over a year later.

**Comment by gwideman** [comment]
> wow didn't expect you to respond as it's over a year later.

Well, you commented yesterday, causing github to email me. So I came to have a look, and saw my mistake!

**Comment by CommanderGL** [comment]
ahh, u should probably close this issue.
